#!/bin/bash
CADMIUMROOT=$(pwd)
TARGET=duet

set -e

./kernel/build $CADMIUMROOT $TARGET nconfig

cgpt create $1
cgpt add -i 1 -t kernel -b 8192 -s 65536 -l Kernel -S 1 -T 5 -P 10 $1
cgpt add -i 2 -t data -b 73728 -s $(expr $(cgpt show /dev/sdc | grep 'Sec GPT table' | awk '{print $1}') - 73728) -l Root $1

partx -a $1

ls ${1}1
sudo dd if=tmp/linux/vmlinux.kpart of=${1}1

sudo ./fs/build $CADMIUMROOT $TARGET ${1}2

sync

