#!/bin/bash
CADMIUMROOT=$(pwd)

. $CADMIUMROOT/config
. $CADMIUMROOT/board/$TARGET/boardinfo
. $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

set -e

echo "You have started the installer script for Cadmium++ If you did not read the Github instructions, please read them. This installer allows you to build directly to a USB drive or to just make a disk image that you can flash later. You have 5 seconds before this program starts installing to your USB device or creating an image."

sleep 5 # let's give user time if they commit a typo

# Usage:
# build-all <device>
# build-all <file> <size>

[ -z "$1" ] && exit 1

if [ -n "$2" ]; then
	echo "You have decided to build a disk image. The installer will now start."
fi

# it deals with env vars
source $CADMIUMROOT/bootfw/$BOOTFW/prepare_parts


# build, package and write kernel
./kernel/build $CADMIUMROOT

# write filesystem
./fs/build $CADMIUMROOT $ROOTPART


./bootfw/$BOOTFW/package $CADMIUMROOT $DEVICE $ROOTPART
dd if=$CADMIUMROOT/tmp/linux-$TARGET/vmlinux.kpart of=$KERNPART

# install modules
make -C $CADMIUMROOT/tmp/linux-$TARGET INSTALL_MOD_PATH=$CADMIUMROOT/tmp/root modules_install

# we don't umount it in fs/build
umount $CADMIUMROOT/tmp/root

# yes, this fails when device is pendrive or sth
losetup -d $DEVICE 2>/dev/null || true

sync

echo "Done!"
