#!/bin/bash
export CADMIUMROOT=$(pwd)
set -e

for RELEASE in bob duet kevin minnie speedy; do
	export RELEASE
	./build-all cadmium-$RELEASE.img 2G || true
	gzip cadmium-$RELEASE.img
	chmod 666 cadmium-$RELEASE.img.gz
done
