#!/bin/bash
export CADMIUMROOT=$(pwd)
set -e

for RELEASE in lazor krane kevin bob minnie speedy; do
	export RELEASE
	./build-all cadmium-$RELEASE.img 2G || true
	gzip cadmium-$RELEASE.img
	chmod 666 cadmium-$RELEASE.img.gz
	sha1sum cadmium-$RELEASE.img.gz > cadmium-$RELEASE.sha1
done
