#!/bin/bash
CADMIUMROOT=$(dirname $(dirname $(dirname $(realpath $0))))

set -e
set -v

[ -z "$CADMIUMROOT" ] && exit 1

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

# sanity check
[ "$BOOTFW" != "pmon" ] && exit 1

cd $CADMIUMROOT/tmp/linux-$ARCH

cp vmlinux $CADMIUMROOT/tmp/root/boot/vmlinux
echo 'default 0
timeout 5
showmenu 1

title Boot d-i
	kernel (usb0,0)/vmlinux
	args console=tty1 root=PARTLABEL=Root' > $CADMIUMROOT/tmp/root/boot/boot.cfg
