#!/bin/bash
set -e

CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"
DESTDIR="$1"

. $CADMIUMROOT/config

mkdir -p "$CADMIUMROOT/tmp"
ROOTFS_TAR="http://os.archlinuxarm.org/os/ArchLinuxARM-$ARCH_ALARM-latest.tar.gz"
if [ ! -f "$CADMIUMROOT/tmp/arch-$ARCH_ALARM.tar.gz" ]; then
	rm $CADMIUMROOT/tmp/arch-$ARCH_ALARM.tar.gz || true
	wget "$ROOTFS_TAR" -O $CADMIUMROOT/tmp/arch-$ARCH_ALARM.tar.gz
fi
tar xfp $CADMIUMROOT/tmp/arch-${ARCH_ALARM}.tar.gz -C $DESTDIR

$chroot $DESTDIR /usr/bin/pacman-key --init
$chroot $DESTDIR /usr/bin/pacman-key --populate archlinuxarm

rm $DESTDIR/etc/resolv.conf # resolv.conf -> /run/systemd/resolve/resolv.conf not working in $chroot
echo "nameserver 1.1.1.1" > $DESTDIR/etc/resolv.conf # TODO: make it configurable or fetch from host?

$chroot $DESTDIR /usr/bin/pacman -Syu --noconfirm networkmanager

$chroot $DESTDIR systemctl start NetworkManager.service
$chroot $DESTDIR systemctl enable NetworkManager.service
