#!/bin/bash
set -e

if [ -z "$DESTDIR" ]; then
	echo "DESTDIR variable is missing!"
	exit 1
fi

mkdir -p "$DESTDIR/var/lib/rmtfs"
for name in fs1 fs2 fsg fsc; do
	dd if=/dev/zero of="$DESTDIR/var/lib/rmtfs/modem_$name" bs=1M count=2
done

cp /etc/systemd/system/rmtfs-dir.service "$DESTDIR/etc/systemd/system/rmtfs-dir.service"
chroot "$DESTDIR" systemctl enable rmtfs-dir
