#!/bin/bash
CADMIUMROOT=$(dirname $(dirname $(realpath $0)))

set -e

[ -z "$TARGET" ] && source $CADMIUMROOT/config

source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

mkdir -p $CADMIUMROOT/tmp
cd $CADMIUMROOT/tmp


# check if kernel has been downloaded this week, if not download/update it
if [ "$(date +'%V%y') $KERNEL" != "$(cat kern-dl-date-$BASEBOARD 2>/dev/null)" ]; then
	echo "Downloading kernel for $BASEBOARD/$TARGET"
	rm -rf linux-$BASEBOARD

	# Using Collabora kernel for ARCH with GNOME 40 
    if [ $ROOTFS = arch ]; then
		curl -L "https://gitlab.collabora.com/eballetbo/linux/-/archive/topic/chromeos/chromeos-5.14/linux-topic-chromeos-chromeos-5.14.tar.gz" -o Linux-archive
	elif [ $KERNEL = libre ]; then
		curl -L "https://linux-libre.fsfla.org/pub/linux-libre/releases/LATEST-5.N/$(curl https://linux-libre.fsfla.org/pub/linux-libre/releases/LATEST-5.N/ | egrep -o 'linux-libre-....-gnu.tar.xz' | head -n1)" -o Linux-archive
    else
		curl -L "$(curl -sL https://www.kernel.org/ | grep "Download complete tarball" | head -n1 | tr '"' ' ' | awk '{print $3}')" -o Linux-archive
	fi
	mkdir linux-$BASEBOARD
	bsdtar xf Linux-archive --strip-components=1 -C linux-$BASEBOARD
	echo "$(date +'%V%y') $KERNEL" > kern-dl-date-$BASEBOARD

	cd linux-$BASEBOARD

	# Collabora kernel has it's own patches applied to source tree
	if  [ $ROOTFS = arch ]; then
		echo "ARCH using Collabora Kernel"
	else	
	  for x in $(ls $CADMIUMROOT/baseboard/$BASEBOARD/patches/*.patch | grep -v IGNORE); do
	  	echo "Applying $x"
	  	patch -p1 --forward < $x
	  done
	  for x in $(ls $CADMIUMROOT/board/$TARGET/patches/*.patch | grep -v IGNORE); do
	  	echo "Applying $x"
	  	patch -p1 --forward < $x
	  done

	  patch -p1 --forward < $CADMIUMROOT/kernel/patches/android-enable-building-ashmem-and-binder-as-modules.patch || true
	  patch -p1 --forward < $CADMIUMROOT/kernel/patches/export-symbols-needed-by-android-drivers.patch.alt || true
	fi
fi

cd $CADMIUMROOT/tmp/linux-$BASEBOARD

# TODO:
# make cadmium defconfig from: common-defconfig, soc-defconfig and board-defconfig
if  [ $ROOTFS = arch ]; then
    [ -f .config ] || cp $CADMIUMROOT/baseboard/$BASEBOARD/kernel-config.arch .config
else  
	[ -f .config ] || cp $CADMIUMROOT/baseboard/$BASEBOARD/kernel-config .config
fi

if [ $KERNEL = libre ]; then
	# it looks better this way
	sed -i'' 's/cadmium/-cadmium/' .config
fi

#make nconfig # if you want to customize config just uncomment this

echo Bulding $KERNEL kernel for $BASEBOARD/$TARGET/$ARCH in $(pwd) with $(nproc) threads using $CROSS_COMPILE
time make -j$(nproc)

# decompression in depthcharge exists only for arm64 devices
[ "$ARCH" != arm ] && lz4 -z -f -k arch/$ARCH/boot/Image c_linux.lz4

make tarxz-pkg
