#!/bin/bash
CADMIUMROOT=$(dirname $(dirname $(realpath $0)))

set -e

[ -z "$TARGET" ] && source $CADMIUMROOT/config

source $CADMIUMROOT/flavor/$FLAV

mkdir -p $CADMIUMROOT/tmp
cd $CADMIUMROOT/tmp


# check if kernel has been downloaded this week, if not download/update it
if [ "$(date +'%V%y')" != "$(cat kern-dl-date-$ARCH 2>/dev/null)" ]; then
	echo "Downloading kernel for $ARCH"
	rm -rf linux-$ARCH

	curl -L "$(curl -sL https://www.kernel.org/ | grep "Download complete tarball" | head -n1 | tr '"' ' ' | awk '{print $3}')" -o Linux-archive
	mkdir linux-$ARCH
	bsdtar xf Linux-archive --strip-components=1 -C linux-$ARCH

	cd linux-$ARCH

	for x in $(ls $CADMIUMROOT/kernel/patches/*.patch); do
		echo "Applying $x"
		patch -p1 --forward < $x
	done

	echo "$(date +'%V%y')" > $CADMIUMROOT/tmp/kern-dl-date-$ARCH
fi

cd $CADMIUMROOT/tmp/linux-$ARCH

[ -f .config ] || cp $CADMIUMROOT/kernel/config.$ARCH .config

#make nconfig LLVM=1 # if you want to customize config just uncomment this

echo "Bulding kernel for $ARCH in $(pwd) with $THREADS threads"
time make -j"$THREADS" LLVM=1
