#!/bin/bash
CADMIUMROOT=$1
DEVICE=$2
KERNPART=$3
ROOTPART=$4

if [ -z "$4" ]; then
	KERNPART=${DEVICE}1
	ROOTPART=${DEVICE}3
fi

shopt -s expand_aliases # needed for aliases
set -e

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

# set up alias areweontarget so "if areweontarget; then X" works fine
if cat /sys/firmware/devicetree/base/compatible 2>/dev/null | egrep -si "$BASEBOARD|$BOARD" ; then
	if [ -z "$DEV" ]; then
		alias areweontarget=true
	else
		alias areweontarget=false
	fi
else
	alias areweontarget=false
fi

areweontarget || mount $ROOTPART /mnt

cd $CADMIUMROOT/tmp/linux-$ARCH

mkimage -D "-I dts -O dtb -p 2048" -f kernel.its vmlinux.uimg || true

dd if=/dev/zero of=bootloader.bin bs=512 count=1
vbutil_kernel --pack vmlinux.kpart \
	--version 1 \
	--vmlinuz vmlinux.uimg \
	--arch $ARCH \
	--keyblock /usr/share/vboot/devkeys/kernel.keyblock \
	--signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk \
	--config cmdline \
	--bootloader bootloader.bin

# make file that would be exactly kernel partition to check sha
dd if=/dev/zero of=vmlinux.kpart.pad bs=1M count=32
dd if=vmlinux.kpart of=vmlinux.kpart.pad bs=32M conv=notrunc

if areweontarget; then
	make modules_install

	INSHA=$(sha1sum vmlinux.kpart.pad)

	if ls /dev/mmcblk1p1 2>/dev/null; then
		MMCDEV=/dev/mmcblk1p1
	else
		MMCDEV=/dev/mmcblk0p1
	fi

	dd if=$MMCDEV of=$CADMIUMROOT/tmp/backup bs=1M count=32 status=none
	dd if=$CADMIUMROOT/tmp/linux-$ARCH/vmlinux.kpart.pad of=$MMCDEV status=none
	OUTSHA=$(sha1sum $MMCDEV)


	if cmp -s -- "$CADMIUMROOT/tmp/linux-$ARCH/vmlinux.kpart.pad" "$MMCDEV"; then
		echo "Written correctly!"
	else
		echo "Oops, $MMCDEV doesn't match linux kernel image!"
		echo "To rollback to old kernel execute:"
		echo "sudo dd if=$CADMIUMROOT/tmp/backup of=$MMCDEV bs=1M count=32"
	fi
else
	make INSTALL_MOD_PATH=/mnt/ modules_install
	umount /mnt
	dd if=$KERNPART of=$CADMIUMROOT/tmp/backup bs=1M count=32 # backup kernel partition, just in case
	dd if=$CADMIUMROOT/tmp/linux-$ARCH/vmlinux.kpart.pad of=$KERNPART
fi

rm $CADMIUMROOT/tmp/linux-$ARCH/vmlinux.uimg

sync
