#!/bin/bash
CADMIUMROOT=$(dirname $(dirname $(realpath $0)))

set -e

[ -z "$TARGET" ] && source $CADMIUMROOT/config

source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

mkdir -p $CADMIUMROOT/tmp
cd $CADMIUMROOT/tmp/linux-$ARCH

# make tar package *manually*
mkdir -p cd-tar
make modules_install INSTALL_MOD_PATH=$CADMIUMROOT/tmp/linux-$ARCH/cd-tar/

echo "$ARCH" > $CADMIUMROOT/tmp/linux-$ARCH/cd-tar/arch
echo "$BOOTFW" > $CADMIUMROOT/tmp/linux-$ARCH/cd-tar/bootfw
make kernelrelease > $CADMIUMROOT/tmp/linux-$ARCH/cd-tar/rel

$CADMIUMROOT/bootfw/$BOOTFW/dump

tar cJf $CADMIUMROOT/tmp/linux-$ARCH.tar.xz -C $CADMIUMROOT/tmp/linux-$ARCH/cd-tar ./
