#!/bin/bash
CADMIUMROOT=$1

shopt -s expand_aliases # needed for aliases
set -e
set -v

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

uname -a > $CADMIUMROOT/tmp/linux-good

cd $CADMIUMROOT/tmp/linux-$BASEBOARD

make modules_install

# FIXME: board-specific, maybe add $DTB to boardinfo?
kexec -s -l --reuse-cmdline --dtb=$2 arch/arm64/boot/Image

echo 'Now execute systemctl kexec to reboot to test kernel'

sync
