#!/bin/bash
# if anything fails bail out
set -e 

# partlabels boiiiiiiiiii
export KERNA=/dev/disk/by-partlabel/MMCKernelA
export KERNB=/dev/disk/by-partlabel/MMCKernelB

export CADMIUMROOT=$1

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

cd $CADMIUMROOT
cd $CADMIUMROOT/tmp/linux-test/ || cd $CADMIUMROOT/tmp/linux-$TARGET


# repack kernel
[ -f 'vmlinux.uimg' ] && rm vmlinux.uimg
mkimage -D "-I dts -O dtb -p 2048" -f kernel.its vmlinux.uimg || true
dd if=/dev/zero of=bootloader.bin bs=512 count=1
vbutil_kernel --pack vmlinux.kpart \
        --version 1 \
        --vmlinuz vmlinux.uimg \
        --arch $ARCH \
        --keyblock /usr/share/vboot/devkeys/kernel.keyblock \
        --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk \
        --config cmdline \
        --bootloader bootloader.bin
rm vmlinux.uimg

# set tries to one
cgpt add -i 2 -t kernel -b 73728 -s 65536 -l MMCKernelB -S 0 -T 1 -P 15 /dev/mmcblk?

make modules_install

# write new kernel

dd if=$CADMIUMROOT/tmp/linux-$TARGET/vmlinux.kpart of=$KERNB

echo "Save all data and reboot"
