#!/bin/bash
CADMIUMROOT=$1

shopt -s expand_aliases # needed for aliases
set -e
set -v

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

# set up alias areweontarget so "if areweontarget; then X" works fine
if cat /sys/firmware/devicetree/base/compatible | egrep -si "$BASEBOARD|$BOARD"; then

	alias areweontarget=true
else
	alias areweontarget=false
fi

areweontarget || exit 1

uname -a > $CADMIUMROOT/tmp/linux-good

cd $CADMIUMROOT/tmp/linux-$BASEBOARD

make modules_install

kexec -s -l --reuse-cmdline arch/arm64/boot/Image

echo 'Now execute systemctl kexec to reboot to test kernel'

sync
