#!/bin/bash
CADMIUMROOT=$(dirname $(dirname $(realpath $0)))

# if anything fails bail out
set -e 

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

# partlabels boiiiiiiiiii
export KERNA=/dev/disk/by-partlabel/MMCKernelA
export KERNB=/dev/disk/by-partlabel/MMCKernelB

# set tries to one
cgpt add -i 2 -t kernel -b 73728 -s 65536 -l MMCKernelB -S 0 -T 1 -P 15 /dev/mmcblk?

cd $CADMIUMROOT/tmp/linux-$ARCH

make modules_install

# write new kernel

dd if=vmlinux.kpart.p2 of=$KERNB

echo "Save all data and reboot"
