#!/bin/bash
CADMIUMROOT=$1
ROOTPART=$2

set -e
set -v

source $CADMIUMROOT/config

cd $CADMIUMROOT/tmp
mkdir -p root
mkfs.f2fs -f $ROOTPART
mount $ROOTPART root

# if we are on arm64 machine, don't use qemu to execute arm64 code
if [ "$(uname -m)" = "aarch64" ]; then
	echo "Running on ARM64 machine"
	foreign=''
else
	cp $(which qemu-aarch64-static) root/
	qemu=/qemu-aarch64-static
	foreign='--foreign'
	echo "Running on not-ARM64 machine"
fi

cd $CADMIUMROOT/tmp

# rootfs-specific setup
case "$ROOTFS" in
	debian)
		echo "Installing Debian"
		# debootstrap randomly exits with 1, so there's that || true
		debootstrap $foreign --arch=arm64 sid $CADMIUMROOT/tmp/root/ https://deb.debian.org/debian/ || true
		# probably it can be ran on target device with little shim that does that and then execs init
		[ -n "$foreign" ] && chroot root/ /debootstrap/debootstrap --second-stage
		# preinstall packages to have wifi
		chroot root/ $qemu /bin/apt update
		chroot root/ $qemu /bin/apt install -y vim vboot-utils network-manager debootstrap parted f2fs-tools
	;;
	# let's explain this: when void is set, $V is set to -v, so it does 'grep -v musl', printing link without musl
	# when $V is not set, grep is 'grep musl', printing only link with musl
	void)
		V='-v'
	;& # fall-through
	void-musl)
		echo "Installing Void Linux"
		ROOTFS_TAR="$(curl -s -L https://voidlinux.org/download/ | grep aarch64 | tr '"' ' ' | awk '{print $3}' | grep $V musl)"
		if [ ! -f "$ROOTFS_TAR" ]; then
			rm void-aarch64${V}tar.xz || true
			wget $ROOTFS_TAR -O void-aarch64$V.tar.xz # musl: void-aarch64, non-musl: void-aarch64-v

		fi
		tar xfp void-aarch64$V.tar.xz -C $CADMIUMROOT/tmp/root
		cp /etc/resolv.conf root/etc/resolv.conf
		chroot root/ $qemu /bin/xbps-install -Syu xbps
		chroot root/ $qemu /bin/xbps-install -yu
		chroot root/ $qemu /bin/xbps-install -y base-system
		chroot root/ $qemu /bin/xbps-remove -y base-voidstrap
		chroot root/ $qemu /bin/xbps-install -y vim NetworkManager parted f2fs-tools
		cp void-aarch64$V.tar.xz root/void.tar.xz
	;;
esac

# remove root password, this is install medium so it's ok
chroot root/ $qemu /bin/passwd -d root

echo $TARGET > root/etc/hostname # set default hostname in kernel?

# workaround bad touchpad experience on certain boards
mkdir -p $CADMIUMROOT/tmp/root/etc/libinput
[ -f $CADMIUMROOT/board/$TARGET/libinput-quirk ] && cp $CADMIUMROOT/board/$TARGET/libinput-quirk root/etc/libinput/local-overrides.quirks

# copy over firmware
mkdir -p $CADMIUMROOT/tmp/root/lib/firmware
cp -r $CADMIUMROOT/board/$TARGET/firmware/* $CADMIUMROOT/tmp/root/lib/firmware/

# install sway config
mkdir -p $CADMIUMROOT/tmp/root/etc/sway
cp $CADMIUMROOT/board/$TARGET/sway-config $CADMIUMROOT/tmp/root/etc/sway/config

# copy installation scripts, double root is not a typo
# -begin sets up partition and fs, -middle installs distro, -end sets up distro
[ "$ROOTFS" = "void-musl" ] && export ROOTFS=void # those 2 are the same in cadmium
cat $CADMIUMROOT/fs/install-to-emmc-begin $CADMIUMROOT/fs/$ROOTFS/install-to-emmc-middle $CADMIUMROOT/fs/install-to-emmc-end > root/root/install-to-emmc
chmod a+x root/root/install-to-emmc


#umount root # done in /build-all
