#!/bin/bash
CADMIUMROOT=$1
TARGET=$2
PART=$3

set -e
set -v

cd $CADMIUMROOT/tmp
mkdir -p root
mkfs.ext4 $PART
mount $PART root

cp $(which qemu-aarch64-static) root/

qemu-debootstrap --arch=arm64 sid root/ https://deb.debian.org/debian/ || true
echo $TARGET > root/etc/hostname
chroot root/ /qemu-aarch64-static /bin/passwd -d root

mkdir -p root/lib/firmware/ath10k/QCA6174/hw3.0/
cp $CADMIUMROOT/fs/firmware/* root/lib/firmware/ath10k/QCA6174/hw3.0/

cp $CADMIUMROOT/vmlinux.kpart.mmc root/

cp $CADMIUMROOT/fs/install-* root/root/ # copy to /root/ on sd card
chmod a+x root/root/install-*

chroot root/ /qemu-aarch64-static /bin/apt update
chroot root/ /qemu-aarch64-static /bin/apt install -y vim vboot-utils network-manager debootstrap

# umount root # we umount root in build-all
