#!/bin/bash
CADMIUMROOT=$1
TARGET=$2
PART=$3

cd $CADMIUMROOT/tmp
mkdir -p root
mount $3 root
cp $(which qemu-aarch64-static) root/
qemu-debootstrap --arch=arm64 sid root/ https://deb.debian.org/debian/ || true
echo $TARGET > root/etc/hostname
chroot root/ /qemu-aarch64-static /bin/passwd -d root
umount root
