#!/bin/bash
. ~/info

# we need internet, TODO: make this run on voidlinux
nmcli device wifi rescan
sleep 4 # wait for it to show up
nmtui connect

BOOTDEV="/dev/null"

# poke around devices to find cadmium
for device in $(ls -H /dev/disk/by-id/* | grep -v part); do
	cgpt show $(readlink -f $device) | grep -q SD && export BOOTDEV=$(readlink -f $device)
done

BOOTDEV=/dev/sda

if [ $BOOTDEV = /dev/null ]; then
	echo "oh no"
	echo "failed getting current device"
	echo "from list of:"
	readlink -f $(ls -H /dev/disk/by-id/* | grep -v part)
	exit 1  
fi

# it isnt really mmc, but who cares?
cgpt add -i 1 -l MMCKernelA $BOOTDEV
cgpt add -i 2 -l MMCKernelB $BOOTDEV

[ -f /oxide.kpart ] && rm /oxide.kpart

until passwd; do
	echo "Enter root password:"
done

read -p "Enter username, no spaces or big letters: "
useradd -G sudo,video,audio,render -s /bin/bash -m $REPLY

echo "Enter user password:"
until passwd $REPLY; do
	echo "Enter user password:"
done

export USERNAME=$REPLY

source ~/ui/install

echo "Done!"

mv ~/info /CdFiles/info
exec rm -r ~/install-to-here ~/install-to-emmc ~/ui
