#!/bin/bash
set -e

mount /dev/mmcblk?p2 /mnt

rm -rf /mnt/lib/modules
mkdir -p /mnt/lib/modules/$(uname -r)/
cp -r /lib/modules/$(uname -r)/* /mnt/lib/modules/$(uname -r)/

dd if=/vmlinux.kpart.mmc of=/dev/mmcblk?p1

umount /mnt
