#!/bin/bash
set -e

# let's put a wildcard because kernel randomly swaps emmc between mmcblk1 and mmcblk0 on duet
DEV=/dev/mmcblk?

sleep 1

dd if=/dev/zero of=${DEV} bs=1M count=64

parted --script ${DEV} mklabel gpt
cgpt create ${DEV}
cgpt add -i 1 -t kernel	-b 8192		-s 65536 -l Kernel -S 1 -T 2 -P 10 ${DEV}
cgpt add -i 2 -t kernel	-b 73728	-s 65536 -l Kernel -S 0 -T 2 -P 5 ${DEV}
cgpt add -i 3 -t data	-b 139264	-s $(expr $(cgpt show /dev/mmcblk1 | grep 'Sec GPT table' | awk '{print $1}') - 139264) -l Root ${DEV}

sleep 1

# f2fs time boiii
mkfs.f2fs ${DEV}p3

sleep 1

mount ${DEV}p3 /mnt

debootstrap --arch=arm64 sid /mnt https://deb.debian.org/debian/ || true
echo duet > /mnt/etc/hostname

# QCA6174 dislikes upstream firmware, copy one that i stole from chromeos
mkdir -p /mnt/lib/firmware/ath10k/QCA6174/hw3.0/
cp -r /lib/firmware/ath10k/QCA6174/hw3.0/* /mnt/lib/firmware/ath10k/QCA6174/hw3.0/

# copy modules over
mkdir -p /mnt/lib/modules/$(uname -r)/
cp -r /lib/modules/$(uname -r)/* /mnt/lib/modules/$(uname -r)/

# copy kernel from usb pendrive/hdd to internal emmc
dd if=/dev/sda1 of=${DEV}p1

# install packages needed to get wifi working and to be ready to compile stuff
chroot /mnt apt install f2fs-tools git build-essential network-manager locales

# this is last, because if user walks away during install they go back,
# configure their system and have it ready immediately
chroot /mnt dpkg-reconfigure tzdata
chroot /mnt dpkg-reconfigure locales

echo "Enter root password:"
chroot /mnt passwd

read -p "Enter username, no spaces or big letters: "
chroot /mnt useradd -G sudo,video,audio -m $REPLY

echo "Enter user password:"
chroot /mnt passwd $REPLY

# TODO: mesa compilation and tell user about it.

# default libinput config for touchpad is bad
# let's override it
mkdir -p /mnt/etc/libinput
cp /etc/libinput/local-overrides.quirks /mnt/etc/libinput/local-overrides.quirks

umount /mnt

echo "Done! :D, Don't forget to install your favourite DE/WM after rebooting"
