#!/bin/bash
set -e

MMCDEV=$(ls /dev/mmcblk* | grep -F boot0 | sed 's/boot0//')

sleep 1

dd if=/dev/zero of=${MMCDEV} bs=1M count=64

parted --script ${MMCDEV} mklabel gpt
cgpt create ${MMCDEV}
cgpt add -i 1 -t kernel	-b 8192		-s 65536 -l MMCKernelA -S 1 -T 2 -P 10	${MMCDEV}
cgpt add -i 2 -t kernel	-b 73728	-s 65536 -l MMCKernelB -S 0 -T 2 -P 5	${MMCDEV}
cgpt add -i 3 -t data	-b 139264	-s $(expr $(cgpt show ${MMCDEV} | grep 'Sec GPT table' | awk '{print $1}') - 139264) -l Root ${MMCDEV}

sleep 1

partx -a ${MMCDEV} || true

sleep 1

# f2fs time boiii
mkfs.f2fs -f ${MMCDEV}p3
mount ${MMCDEV}p3 /mnt

mkdir -p /mnt/lib/firmware/
cp -r /lib/firmware/* /mnt/lib/firmware/

# sway config
if [ -f /etc/sway/config ]; then
	mkdir -p /mnt/etc/sway
	cp /etc/sway/config /mnt/etc/sway/config
fi

# copy modules over
mkdir -p /mnt/lib/modules/$(uname -r)/
cp -r /lib/modules/$(uname -r)/* /mnt/lib/modules/$(uname -r)/

# copy kernel from usb pendrive/hdd to internal emmc
dd if=/dev/zero of=${MMCDEV}p1 || true
dd if=/dev/disk/by-partlabel/SDKernelA of=${MMCDEV}p1

# end of install-to-emmc-begin
