#!/bin/bash
CADMIUMROOT=$(dirname $(dirname $(realpath $0)))
ROOTPART=$1

set -e
set -v

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

cd $CADMIUMROOT/tmp

mount proc root/proc -t proc

echo "Enter root password:"
until chroot root/ passwd root; do
	echo "Enter root password:"
done

read -p "Enter username, no spaces or big letters: "
chroot /mnt useradd -G sudo,video,audio,render -s /bin/bash -m $REPLY

echo "Enter user password:"
until chroot /mnt passwd $REPLY; do
	echo "Enter user password:"
done

export USERNAME=$REPLY

mkdir -p $CADMIUMROOT/tmp/root/lib/firmware/rmtfs
dd if=/dev/zero bs=1M count=2 of=$CADMIUMROOT/tmp/root/lib/firmware/rmtfs/modem_fs1
dd if=/dev/zero bs=1M count=2 of=$CADMIUMROOT/tmp/root/lib/firmware/rmtfs/modem_fs2
dd if=/dev/zero bs=1M count=2 of=$CADMIUMROOT/tmp/root/lib/firmware/rmtfs/modem_fsg
dd if=/dev/zero bs=1M count=2 of=$CADMIUMROOT/tmp/root/lib/firmware/rmtfs/modem_fsc

git clone https://github.com/andersson/qmic.git $CADMIUMROOT/tmp/root/CdFiles/qmic
git clone https://github.com/andersson/qrtr.git $CADMIUMROOT/tmp/root/CdFiles/qrtr
git clone https://github.com/Maccraft123/rmtfs.git $CADMIUMROOT/tmp/root/CdFiles/rmtfs

chroot $CADMIUMROOT/tmp/root/ make -C /CdFiles/qmic clean
chroot $CADMIUMROOT/tmp/root/ make -C /CdFiles/qrtr clean
chroot $CADMIUMROOT/tmp/root/ make -C /CdFiles/rmtfs clean
chroot $CADMIUMROOT/tmp/root/ make -C /CdFiles/qmic prefix=/usr install
chroot $CADMIUMROOT/tmp/root/ make -C /CdFiles/qrtr prefix=/usr install
chroot $CADMIUMROOT/tmp/root/ make -C /CdFiles/rmtfs prefix=/usr install
chroot $CADMIUMROOT/tmp/root/ systemctl enable rmtfs

export CHRT="chroot $CADMIUMROOT/tmp/root"
export INST_EMMC=1
source $CADMIUMROOT/ui/install

umount $CADMIUMROOT/tmp/root/proc
