#!/bin/bash
CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"

set -e

echo "Packaging kernel for depthcharge machines"

[ -z "$CADMIUMROOT" ] && exit 1

VBUTIL_KERNEL=""
if which vbutil_kernel >/dev/null 2>&1; then
	VBUTIL_KERNEL="vbutil_kernel"
elif which futility >/dev/null 2>&1; then
	VBUTIL_KERNEL="futility vbutil_kernel"
else
	echo "vbutil_kernel not found"
	exit 1
fi

source "$CADMIUMROOT/config"
source "$CADMIUMROOT/flavor/$FLAV"

cd "$CADMIUMROOT/tmp/linux-$ARCH"

if [ "$ARCH" = "arm64" ]; then
	COMPRESSION="lz4"
	IMAGE="c_linux.lz4"
	lz4 -z --best -f "arch/$ARCH/boot/Image" c_linux.lz4
else
	COMPRESSION="none"
	IMAGE="arch/arm/boot/zImage"
fi

cp "$CADMIUMROOT/kernel/cmdline" cmdline
cp "$CADMIUMROOT/kernel/cmdline" cmdline.p2
echo ' root=PARTUUID=%U/PARTNROFF=2' >> cmdline
echo ' root=PARTUUID=%U/PARTNROFF=1' >> cmdline.p2

# https://github.com/archlinuxarm/PKGBUILDs/blob/master/core/linux-aarch64/PKGBUILD
for B in veyron elm gru kukui trogdor; do
	DTBS="$DTBS $(find arch/$ARCH/boot/dts -name \*${B}\*.dtb)"
done

echo $DTBS | "$CADMIUMROOT/loader/depthcharge/generate_chromebook_its.sh" "$IMAGE" "$ARCH" "$COMPRESSION" > kernel.its

mkimage -D "-I dts -O dtb -p 2048" -f kernel.its vmlinux.uimg

dd if=/dev/zero of=bootloader.bin bs=512 count=1
$VBUTIL_KERNEL --pack vmlinux.kpart \
	--version 1 \
	--vmlinuz vmlinux.uimg \
	--arch arm \
	--keyblock /usr/share/vboot/devkeys/kernel.keyblock \
	--signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk \
	--config cmdline \
	--bootloader bootloader.bin

cp vmlinux.kpart "$CADMIUMROOT/tmp/"
dd if="vmlinux.kpart" of="$KERNPART" conv=fsync

$VBUTIL_KERNEL --pack vmlinux.kpart.p2 \
	--version 1 \
	--vmlinuz vmlinux.uimg \
	--arch arm \
	--keyblock /usr/share/vboot/devkeys/kernel.keyblock \
	--signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk \
	--config cmdline.p2 \
	--bootloader bootloader.bin

cp vmlinux.kpart.p2 "$CADMIUMROOT/tmp/"
