#!/bin/bash
CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"

set -e
set -x

echo "Making it bootable on EFI devices"

source "$CADMIUMROOT/config"
source "$CADMIUMROOT/flavor/$FLAV"

export $(blkid --output export $ROOTPART | grep -E '^PARTUUID=.*')
export CMDLINE="$(< $CADMIUMROOT/kernel/cmdline) rootfstype=$FILESYSTEM root=PARTUUID=$PARTUUID"

function umount_boot() {
	echo "Unmounting ESP"
	umount "$CADMIUMROOT/tmp/boot"
}

# i would love to use UKI for that, but it doesn't work on lenovo yoga slim 7x

mkdir -p "$CADMIUMROOT/tmp/boot"
mount "$BOOTPART" "$CADMIUMROOT/tmp/boot"
trap umount_boot EXIT

mkdir -p "$CADMIUMROOT/tmp/boot/efi/boot/"
mkdir -p "$CADMIUMROOT/tmp/boot/efi/systemd/drivers/"
mkdir -p "$CADMIUMROOT/tmp/boot/loader/entries"
# FIXME: x1e doesn't boot without clk_ignore_unused
echo "title Start Cadmium
linux /Image
options $CMDLINE clk_ignore_unused
architecture aa64" > "$CADMIUMROOT/tmp/boot/loader/entries/cadmium.conf"
echo "default @saved
timeout 5
console-mode max" > "$CADMIUMROOT/tmp/boot/loader/loader.conf"

"$CADMIUMROOT/loader/efi/fetch_sdboot" "$ARCH" "$CADMIUMROOT/tmp/boot/efi/boot/bootaa64.efi"
"$CADMIUMROOT/loader/efi/fetch_dtbloader" "$CADMIUMROOT/tmp/boot/efi/systemd/drivers/dtbloaderaa64.efi"

make -C "$CADMIUMROOT/tmp/linux-$ARCH/" INSTALL_DTBS_PATH="$CADMIUMROOT/tmp/boot/dtbs/" dtbs_install
cp "$CADMIUMROOT/tmp/linux-$ARCH/arch/$ARCH/boot/Image" "$CADMIUMROOT/tmp/boot/"
