#!/bin/bash
CADMIUMROOT=$(dirname $(dirname $(dirname $(realpath $0))))

set -e
set -v

echo "Packaging kernel for depthcharge machines"

[ -z "$CADMIUMROOT" ] && exit 1

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

# sanity check
[ "$BOOTFW" != "depthcharge" ] && exit 1

cd $CADMIUMROOT/tmp/linux-$ARCH

cp vmlinux.kpart cd-tar/
cp vmlinux.kpart.p2 cd-tar/
cp oxide.kpart cd-tar/
