#!/bin/bash
CADMIUMROOT=$1

set -e
set -v

echo "Making .tar.xz kernel package for depthcharge machines"

[ -z "$CADMIUMROOT" ] && exit 1

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

# sanity check
[ "$BOOTFW" != "depthcharge" ] && exit 1

cd $CADMIUMROOT/tmp/linux-$BASEBOARD

REL=$(make kernelrelease)

# just in case we are building 2 targets immediately after each other
[ -d $CADMIUMROOT/tmp/repack-$BASEBOARD ] && rm -rf $CADMIUMROOT/tmp/repack-$BASEBOARD
mkdir $CADMIUMROOT/tmp/repack-$BASEBOARD

# we have to add vmlinux.kpart and few other things
bsdtar xf $CADMIUMROOT/tmp/linux-$BASEBOARD/linux*cadmium*.tar.xz -C $CADMIUMROOT/tmp/repack-$BASEBOARD

cd $CADMIUMROOT

cp $CADMIUMROOT/tmp/linux-$BASEBOARD/vmlinux.kpart $CADMIUMROOT/tmp/repack-$BASEBOARD/vmlinux.kpart

echo $REL > $CADMIUMROOT/tmp/repack-$BASEBOARD/kern-release
echo $BASEBOARD > $CADMIUMROOT/tmp/repack-$BASEBOARD/target

# and pack it again
cd $CADMIUMROOT
tar cJf $CADMIUMROOT/repack-$BASEBOARD.tar.xz -C $CADMIUMROOT/tmp repack-$BASEBOARD

# just to be safe
sha1sum $CADMIUMROOT/repack-$BASEBOARD.tar.xz > $CADMIUMROOT/repack-$BASEBOARD.sha1
