#!/bin/bash
CADMIUMROOT=$1

set -e
set -v

echo "Making .tar.xz kernel package for depthcharge machines"

[ -z "$CADMIUMROOT" ] && exit 1

source $CADMIUMROOT/config
source $CADMIUMROOT/board/$TARGET/boardinfo
source $CADMIUMROOT/baseboard/$BASEBOARD/boardinfo

# sanity check
[ "$BOOTFW" != "depthcharge" ] && exit 1

cd $CADMIUMROOT/tmp/linux-$TARGET

REL=$(make kernelrelease)

# just in case we are building 2 targets immediately after each other
[ -d $CADMIUMROOT/tmp/repack-$TARGET ] && rm -rf $CADMIUMROOT/tmp/repack-$TARGET
mkdir $CADMIUMROOT/tmp/repack-$TARGET

# we have to add vmlinux.kpart and few other things
bsdtar xf $CADMIUMROOT/tmp/linux-$TARGET/linux*cadmium*.tar.xz -C $CADMIUMROOT/tmp/repack-$TARGET

cp $CADMIUMROOT/tmp/linux-$TARGET/vmlinux.kpart $CADMIUMROOT/tmp/repack-$TARGET/vmlinux.kpart

echo $REL > $CADMIUMROOT/tmp/repack-$TARGET/kern-release
echo $TARGET > $CADMIUMROOT/tmp/repack-$TARGET/target

# and pack it again
cd $CADMIUMROOT
tar cJf $CADMIUMROOT/repack-$TARGET.tar.xz -C $CADMIUMROOT/tmp repack-$TARGET

# just to be safe
sha1sum $CADMIUMROOT/repack-$TARGET.tar.xz > $CADMIUMROOT/repack-$TARGET.sha1
