#!/bin/bash
set -e
set -x

CADMIUMROOT=$(dirname $(dirname $(dirname $(realpath $0))))
DESTDIR=$1

. $CADMIUMROOT/config

echo "Installing Void Linux"
ROOTFS_TAR="$(curl -s -L https://voidlinux.org/download/ | grep $ARCH_UNAME | tr '"' ' ' | awk '{print $3}' | grep -v musl)"
if [ ! -f "$ROOTFS_TAR" ]; then
	rm void-${ARCH_UNAME}.tar.xz || true
	wget $ROOTFS_TAR -O void-$ARCH_UNAME.tar.xz # musl: void-aarch64, non-musl: void-aarch64-v

fi
tar xfp void-${ARCH_UNAME}.tar.xz -C $DESTDIR
cp /etc/resolv.conf $DESTDIR/etc/resolv.conf
chroot $DESTDIR $qemu /bin/xbps-install -Syu xbps
chroot $DESTDIR $qemu /bin/xbps-install -Su
chroot $DESTDIR $qemu /bin/xbps-install -yu
chroot $DESTDIR $qemu export XBPS_ARCH=${ARCH_UNAME} 
chroot $DESTDIR $qemu /bin/xbps-install -y base-system dbus NetworkManager
chroot $DESTDIR $qemu /bin/xbps-remove -y base-voidstrap

chroot $DESTDIR $qemu ln -s /etc/sv/dbus /etc/runit/runsvdir/default/
chroot $DESTDIR $qemu ln -s /etc/sv/NetworkManager /etc/runit/runsvdir/default/

chroot $DESTDIR $qemu ln -s /etc/sv/agetty-ttyAMA0 /etc/runit/runsvdir/default/
